
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.2/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.26200 - AMD64
  -
    kind: "find-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.2/Modules/CMakeNinjaFindMake.cmake:5 (find_program)"
      - "CMakeLists.txt:2 (project)"
    mode: "program"
    variable: "CMAKE_MAKE_PROGRAM"
    description: "Program used to build from build.ninja files."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "ninja-build"
      - "ninja"
      - "samu"
    candidate_directories:
      - "C:/Program Files/WindowsApps/Microsoft.PowerShell_7.5.4.0_x64__8wekyb3d8bbwe/"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/debugCommand/"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/copilotCli/"
      - "C:/Windows/System32/"
      - "C:/Windows/"
      - "C:/Windows/System32/wbem/"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/"
      - "C:/Windows/System32/OpenSSH/"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/"
      - "C:/ProgramData/chocolatey/bin/"
      - "C:/ProgramData/mingw64/mingw64/bin/"
      - "C:/Program Files/Git/cmd/"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/"
      - "C:/Program Files/dotnet/"
      - "C:/Program Files/CMake/bin/"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Local/Microsoft/WindowsApps/"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Local/Programs/Microsoft VS Code/bin/"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Local/Programs/Zed/bin/"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Local/PowerToys/DSCModules/"
    searched_directories:
      - "C:/Program Files/WindowsApps/Microsoft.PowerShell_7.5.4.0_x64__8wekyb3d8bbwe/ninja-build.com"
      - "C:/Program Files/WindowsApps/Microsoft.PowerShell_7.5.4.0_x64__8wekyb3d8bbwe/ninja-build.exe"
      - "C:/Program Files/WindowsApps/Microsoft.PowerShell_7.5.4.0_x64__8wekyb3d8bbwe/ninja-build"
      - "C:/Program Files/WindowsApps/Microsoft.PowerShell_7.5.4.0_x64__8wekyb3d8bbwe/ninja.com"
      - "C:/Program Files/WindowsApps/Microsoft.PowerShell_7.5.4.0_x64__8wekyb3d8bbwe/ninja.exe"
      - "C:/Program Files/WindowsApps/Microsoft.PowerShell_7.5.4.0_x64__8wekyb3d8bbwe/ninja"
      - "C:/Program Files/WindowsApps/Microsoft.PowerShell_7.5.4.0_x64__8wekyb3d8bbwe/samu.com"
      - "C:/Program Files/WindowsApps/Microsoft.PowerShell_7.5.4.0_x64__8wekyb3d8bbwe/samu.exe"
      - "C:/Program Files/WindowsApps/Microsoft.PowerShell_7.5.4.0_x64__8wekyb3d8bbwe/samu"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/debugCommand/ninja-build.com"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/debugCommand/ninja-build.exe"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/debugCommand/ninja-build"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/debugCommand/ninja.com"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/debugCommand/ninja.exe"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/debugCommand/ninja"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/debugCommand/samu.com"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/debugCommand/samu.exe"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/debugCommand/samu"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/copilotCli/ninja-build.com"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/copilotCli/ninja-build.exe"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/copilotCli/ninja-build"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/copilotCli/ninja.com"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/copilotCli/ninja.exe"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/copilotCli/ninja"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/copilotCli/samu.com"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/copilotCli/samu.exe"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/copilotCli/samu"
      - "C:/Windows/System32/ninja-build.com"
      - "C:/Windows/System32/ninja-build.exe"
      - "C:/Windows/System32/ninja-build"
      - "C:/Windows/System32/ninja.com"
      - "C:/Windows/System32/ninja.exe"
      - "C:/Windows/System32/ninja"
      - "C:/Windows/System32/samu.com"
      - "C:/Windows/System32/samu.exe"
      - "C:/Windows/System32/samu"
      - "C:/Windows/ninja-build.com"
      - "C:/Windows/ninja-build.exe"
      - "C:/Windows/ninja-build"
      - "C:/Windows/ninja.com"
      - "C:/Windows/ninja.exe"
      - "C:/Windows/ninja"
      - "C:/Windows/samu.com"
      - "C:/Windows/samu.exe"
      - "C:/Windows/samu"
      - "C:/Windows/System32/wbem/ninja-build.com"
      - "C:/Windows/System32/wbem/ninja-build.exe"
      - "C:/Windows/System32/wbem/ninja-build"
      - "C:/Windows/System32/wbem/ninja.com"
      - "C:/Windows/System32/wbem/ninja.exe"
      - "C:/Windows/System32/wbem/ninja"
      - "C:/Windows/System32/wbem/samu.com"
      - "C:/Windows/System32/wbem/samu.exe"
      - "C:/Windows/System32/wbem/samu"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja-build.com"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja-build.exe"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja-build"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja.com"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja.exe"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/samu.com"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/samu.exe"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/samu"
      - "C:/Windows/System32/OpenSSH/ninja-build.com"
      - "C:/Windows/System32/OpenSSH/ninja-build.exe"
      - "C:/Windows/System32/OpenSSH/ninja-build"
      - "C:/Windows/System32/OpenSSH/ninja.com"
      - "C:/Windows/System32/OpenSSH/ninja.exe"
      - "C:/Windows/System32/OpenSSH/ninja"
      - "C:/Windows/System32/OpenSSH/samu.com"
      - "C:/Windows/System32/OpenSSH/samu.exe"
      - "C:/Windows/System32/OpenSSH/samu"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/ninja-build.com"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/ninja-build.exe"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/ninja-build"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/ninja.com"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/ninja.exe"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/ninja"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/samu.com"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/samu.exe"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/samu"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/ninja-build.com"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/ninja-build.exe"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/ninja-build"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/ninja.com"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/ninja.exe"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/ninja"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/samu.com"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/samu.exe"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/samu"
      - "C:/ProgramData/chocolatey/bin/ninja-build.com"
      - "C:/ProgramData/chocolatey/bin/ninja-build.exe"
      - "C:/ProgramData/chocolatey/bin/ninja-build"
      - "C:/ProgramData/chocolatey/bin/ninja.com"
      - "C:/ProgramData/chocolatey/bin/ninja.exe"
      - "C:/ProgramData/chocolatey/bin/ninja"
      - "C:/ProgramData/chocolatey/bin/samu.com"
      - "C:/ProgramData/chocolatey/bin/samu.exe"
      - "C:/ProgramData/chocolatey/bin/samu"
      - "C:/ProgramData/mingw64/mingw64/bin/ninja-build.com"
      - "C:/ProgramData/mingw64/mingw64/bin/ninja-build.exe"
      - "C:/ProgramData/mingw64/mingw64/bin/ninja-build"
      - "C:/ProgramData/mingw64/mingw64/bin/ninja.com"
      - "C:/ProgramData/mingw64/mingw64/bin/ninja.exe"
      - "C:/ProgramData/mingw64/mingw64/bin/ninja"
      - "C:/ProgramData/mingw64/mingw64/bin/samu.com"
      - "C:/ProgramData/mingw64/mingw64/bin/samu.exe"
      - "C:/ProgramData/mingw64/mingw64/bin/samu"
      - "C:/Program Files/Git/cmd/ninja-build.com"
      - "C:/Program Files/Git/cmd/ninja-build.exe"
      - "C:/Program Files/Git/cmd/ninja-build"
      - "C:/Program Files/Git/cmd/ninja.com"
      - "C:/Program Files/Git/cmd/ninja.exe"
      - "C:/Program Files/Git/cmd/ninja"
      - "C:/Program Files/Git/cmd/samu.com"
      - "C:/Program Files/Git/cmd/samu.exe"
      - "C:/Program Files/Git/cmd/samu"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/ninja-build.com"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/ninja-build.exe"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/ninja-build"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/ninja.com"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/ninja.exe"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/ninja"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/samu.com"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/samu.exe"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/samu"
      - "C:/Program Files/dotnet/ninja-build.com"
      - "C:/Program Files/dotnet/ninja-build.exe"
      - "C:/Program Files/dotnet/ninja-build"
      - "C:/Program Files/dotnet/ninja.com"
      - "C:/Program Files/dotnet/ninja.exe"
      - "C:/Program Files/dotnet/ninja"
      - "C:/Program Files/dotnet/samu.com"
      - "C:/Program Files/dotnet/samu.exe"
      - "C:/Program Files/dotnet/samu"
      - "C:/Program Files/CMake/bin/ninja-build.com"
      - "C:/Program Files/CMake/bin/ninja-build.exe"
      - "C:/Program Files/CMake/bin/ninja-build"
      - "C:/Program Files/CMake/bin/ninja.com"
      - "C:/Program Files/CMake/bin/ninja.exe"
      - "C:/Program Files/CMake/bin/ninja"
      - "C:/Program Files/CMake/bin/samu.com"
      - "C:/Program Files/CMake/bin/samu.exe"
      - "C:/Program Files/CMake/bin/samu"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Local/Microsoft/WindowsApps/ninja-build.com"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Local/Microsoft/WindowsApps/ninja-build.exe"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Local/Microsoft/WindowsApps/ninja-build"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Local/Microsoft/WindowsApps/ninja.com"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Local/Microsoft/WindowsApps/ninja.exe"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Local/Microsoft/WindowsApps/ninja"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Local/Microsoft/WindowsApps/samu.com"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Local/Microsoft/WindowsApps/samu.exe"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Local/Microsoft/WindowsApps/samu"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Local/Programs/Microsoft VS Code/bin/ninja-build.com"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Local/Programs/Microsoft VS Code/bin/ninja-build.exe"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Local/Programs/Microsoft VS Code/bin/ninja-build"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Local/Programs/Microsoft VS Code/bin/ninja.com"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Local/Programs/Microsoft VS Code/bin/ninja.exe"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Local/Programs/Microsoft VS Code/bin/ninja"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Local/Programs/Microsoft VS Code/bin/samu.com"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Local/Programs/Microsoft VS Code/bin/samu.exe"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Local/Programs/Microsoft VS Code/bin/samu"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Local/Programs/Zed/bin/ninja-build.com"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Local/Programs/Zed/bin/ninja-build.exe"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Local/Programs/Zed/bin/ninja-build"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Local/Programs/Zed/bin/ninja.com"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Local/Programs/Zed/bin/ninja.exe"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Local/Programs/Zed/bin/ninja"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Local/Programs/Zed/bin/samu.com"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Local/Programs/Zed/bin/samu.exe"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Local/Programs/Zed/bin/samu"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Local/PowerToys/DSCModules/ninja-build.com"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Local/PowerToys/DSCModules/ninja-build.exe"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Local/PowerToys/DSCModules/ninja-build"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Local/PowerToys/DSCModules/ninja.com"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Local/PowerToys/DSCModules/ninja.exe"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Local/PowerToys/DSCModules/ninja"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Local/PowerToys/DSCModules/samu.com"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Local/PowerToys/DSCModules/samu.exe"
      - "C:/Users/matth.INSTAR-MOONBASE/AppData/Local/PowerToys/DSCModules/samu"
    found: false
    search_context:
      ENV{PATH}:
        - "C:\\Program Files\\WindowsApps\\Microsoft.PowerShell_7.5.4.0_x64__8wekyb3d8bbwe"
        - "c:\\Users\\matth.INSTAR-MOONBASE\\AppData\\Roaming\\Code\\User\\globalStorage\\github.copilot-chat\\debugCommand"
        - "c:\\Users\\matth.INSTAR-MOONBASE\\AppData\\Roaming\\Code\\User\\globalStorage\\github.copilot-chat\\copilotCli"
        - "C:\\WINDOWS\\system32"
        - "C:\\WINDOWS"
        - "C:\\WINDOWS\\System32\\Wbem"
        - "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\WINDOWS\\System32\\OpenSSH\\"
        - "C:\\Program Files\\NVIDIA Corporation\\NVIDIA App\\NvDLISR"
        - "C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common"
        - "C:\\ProgramData\\chocolatey\\bin"
        - "C:\\ProgramData\\mingw64\\mingw64\\bin"
        - "C:\\Program Files\\Git\\cmd"
        - "C:\\Program Files (x86)\\Windows Kits\\10\\Windows Performance Toolkit\\"
        - "C:\\Program Files\\dotnet\\"
        - "C:\\Program Files\\CMake\\bin"
        - "C:\\Users\\matth.INSTAR-MOONBASE\\AppData\\Local\\Microsoft\\WindowsApps"
        - "C:\\Users\\matth.INSTAR-MOONBASE\\AppData\\Local\\Programs\\Microsoft VS Code\\bin"
        - "C:\\Users\\matth.INSTAR-MOONBASE\\AppData\\Local\\Programs\\Zed\\bin"
        - "C:\\Users\\matth.INSTAR-MOONBASE\\AppData\\Local\\PowerToys\\DSCModules\\"
...
